<a href="https://colab.research.google.com/github/PaulToronto/Hong-Kong-University-of-Science-and-Technology-Coursera-Matrix-Algebra-for-Engineers/blob/main/1_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1 Matrices

In [1]:
import sympy as sym
import numpy as np

## 1.1 Matrix Definitions

A **matrix** is a rectangular array of numbers. The numbers can be symbols. 

$$
A = 
\left[
\begin{matrix}
a & b \\
c & d
\end{matrix}
\right],
B = 
\left[
\begin{matrix}
a & b \\ 
c & d \\
e & f
\end{matrix}
\right],
C = 
\left[
\begin{matrix}
a & b & c \\
d & e & f
\end{matrix}
\right]
$$

- $A$ is a $2 \times 2$ matrix
- $B$ is a $3 \times 2$ matrix
- $C$ is a $2 \times 3$ matrix. 

In [2]:
a, b, c, d, e, f = sym.symbols('a b c d e f')

In [3]:
A = sym.Matrix([[a,  b],
                [c, d]])

B = sym.Matrix([[a, b],
                [c, d],
                [e, f]])

C = sym.Matrix([[a, b, c],
                [d, e, f]])

In [4]:
A

Matrix([
[a, b],
[c, d]])

In [5]:
B

Matrix([
[a, b],
[c, d],
[e, f]])

In [6]:
C

Matrix([
[a, b, c],
[d, e, f]])

$$
x = 
\left[
\begin{matrix}
a \\
b \\
c
\end{matrix}
\right],
y = 
\left[
\begin{matrix}
a & b & c
\end{matrix}
\right]
$$

- $x$ is a **column vector** or a $3 \times 1$ matrix
- $y$ is a  **row vector** or a $1 \times 3$ matrix

### A General Matrix

$$
A_{m \times n} = 
\left[
\begin{matrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{matrix}
\right]
$$

### Matrix Addition

- Two matrices can be only be added together when they have the same dimensions

In [7]:
a, b, c, d, e, f, g, h = sym.symbols('a b c d e f g h')

A = sym.Matrix([[a, b],
                [c, d]])

B = sym.Matrix([[e, f],
                [g, h]])

In [8]:
A

Matrix([
[a, b],
[c, d]])

In [9]:
B

Matrix([
[e, f],
[g, h]])

In [10]:
A + B

Matrix([
[a + e, b + f],
[c + g, d + h]])

### Multiply a Matrix by a Scalar

In [11]:
k = sym.symbols('k')

k * A

Matrix([
[a*k, b*k],
[c*k, d*k]])

### Matrix Multiplication

- Note that matrix muliplication is **not commutative**
- An $m \times n$ matrix can only be multiplied by an $n \times p$ matrix
    - The values $m$ and $p$ are arbitrary
    - The number of columns in the first matrix ($n$) must be equal to the number of rows in the second matrix ($n$)
        - The result is an $m \times p$ matrix

In [12]:
A * B

Matrix([
[a*e + b*g, a*f + b*h],
[c*e + d*g, c*f + d*h]])

In [13]:
# alternately
sym.Matrix([[A.row(0).dot(B.col(0)), A.row(0).dot(B.col(1))],
            [A.row(1).dot(B.col(0)), A.row(1).dot(B.col(1))]])

Matrix([
[a*e + b*g, a*f + b*h],
[c*e + d*g, c*f + d*h]])

In [14]:
A.row(0) * B.col(0), A.row(0).dot(B.col(0))

(Matrix([[a*e + b*g]]), a*e + b*g)

In [15]:
type(A.row(0) * B.col(0)), type(A.row(0).dot(B.col(0)))

(sympy.matrices.dense.MutableDenseMatrix, sympy.core.add.Add)

In [16]:
B * A

Matrix([
[a*e + c*f, b*e + d*f],
[a*g + c*h, b*g + d*h]])

In [17]:
A * B == A * B, A * B == B * A

(True, False)

#### General Formula for the ${ij}^{th}$  element of the product of two matrices

Let $A$, $B$ and $C$ be matrices such that $C = AB$. Then,

$$
c_{ij} = \sum_{k=1}^{n}{a_{ik}b_{kj}}
$$

#### $AB = AC$ does not imply $B = C$

In [18]:
A = sym.Matrix([[1, 2],
                [2, 4]])

B = sym.Matrix([[2, 1],
                [1, 3]])

C = sym.Matrix([[4, 3],
                [0, 2]])

In [19]:
# sympy
A * B == A * C, B == C

(True, False)

In [20]:
# sympy
(A * B).equals(A * C), B.equals(C)

(True, False)

In [21]:
# numpy
Anp = np.array(A, dtype='int64')
Bnp = np.array(B, dtype='int64')
Cnp = np.array(C, dtype='int64')

np.array_equal(Anp.dot(Bnp), Anp.dot(Cnp)), np.array_equal(B, C)

(True, False)

### Associative Law for Matrix Multiplication

$A(BC) = (AB)C$

### Special Matrices

#### Zero Matrix: $O_{m \times n}$

- The zero matrix is analogous to the scalar 0

$$
O = 
\left[
    \begin{matrix}
    0 & 0 \\
    0 & 0
    \end{matrix}
\right]
$$

This matrix is used a lot in the following equation, where $A$ is an $m \times n$ matrix, x is an $n \times 1$ column vector and the zero matrix is an $m \times 1$ column vector.

$Ax = O$

In [22]:
A = sym.zeros(2, 2)
A

Matrix([
[0, 0],
[0, 0]])

In [23]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [24]:
# note that sympy can also create a matrix of ones
sym.ones(3)

Matrix([
[1, 1, 1],
[1, 1, 1],
[1, 1, 1]])

#### Identity Matrix: $I_{n}$

- The identity matrix, denoted $I$, is analogous to the scalar 1
    - $AI = A = IA$, for any square matrix $A$
- The identity matrix is always a square matrix
- The identity matrix has only ones along the diagonal and zeros everywhere else

In [25]:
sym.eye(3)

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
# note that sympy can use `.eye()` to create
# matrices that are not square, therefore not
# identity matrices
sym.eye(3, 2)

Matrix([
[1, 0],
[0, 1],
[0, 0]])

In [28]:
np.eye(3, 2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

#### Diagonal Matrix

$$
D =
\left[
    \begin{matrix}
    d_1 & 0 & 0 \\
    0 & d_2 & 0 \\
    0 & 0 & d_3 
    \end{matrix}
\right]
$$

In [29]:
sym.diag(1, 2, 3)

Matrix([
[1, 0, 0],
[0, 2, 0],
[0, 0, 3]])

In [30]:
sym.diag(3, 3, 7, 2, 8)

Matrix([
[3, 0, 0, 0, 0],
[0, 3, 0, 0, 0],
[0, 0, 7, 0, 0],
[0, 0, 0, 2, 0],
[0, 0, 0, 0, 8]])

In [31]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [32]:
np.diag([3, 3, 7, 2, 8])

array([[3, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 7, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 8]])

#### Banded Matrix

##### Example: Tridiagonal

In [33]:
# takes a dictionary as an argument
# key 0: the diagnoal
# key -1: the lower diagonal
# key 1: the upper diagonal
# - can extend beyond -1 and 1 
d1, d2, d3 = sym.symbols('d_1 d_2 d_3')
l1, l2 = sym.symbols('l_1 l_2')
u1, u2 = sym.symbols('u_1 u_2')

sym.banded({0: (d1, d2, d3), -1: (l1, l2), 1: (u1, u2)})

Matrix([
[d_1, u_1,   0],
[l_1, d_2, u_2],
[  0, l_2, d_3]])

#### Triangular Matrix

##### Upper Triangular Matrix

In [34]:
a, b, c, d, e, f = sym.symbols('a b c d e f')

U = sym.Matrix([[a, b, c],
                [0, d, e],
                [0, 0, f]])

U

Matrix([
[a, b, c],
[0, d, e],
[0, 0, f]])

##### Lower Triangular Matrix

In [35]:
L = sym.Matrix([[a, 0, 0],
                [b, c, 0],
                [d, e, f]])

L

Matrix([
[a, 0, 0],
[b, c, 0],
[d, e, f]])

### Product of Diagonal Matrices

The product of two diagonal matrices is a diagonal matrix, with elements given by the product of the diagonal elements

In [36]:
a1, a2, a3, b1, b2, b3 = sym.symbols('a_1 a_2 a_3 b_1 b_2 b_3')

A = sym.diag(a1, a2, a3)
B = sym.diag(b1, b2, b3)

In [37]:
A

Matrix([
[a_1,   0,   0],
[  0, a_2,   0],
[  0,   0, a_3]])

In [38]:
B

Matrix([
[b_1,   0,   0],
[  0, b_2,   0],
[  0,   0, b_3]])

In [39]:
A * B

Matrix([
[a_1*b_1,       0,       0],
[      0, a_2*b_2,       0],
[      0,       0, a_3*b_3]])

### Product of Triangular Matrices

The product of two upper triangular matrices is an upper triangular matrix, with the diagonal elements of the product given by the product of the diagonal elements

In [40]:
A = sym.Matrix([[a1, a2],
                [0, a3]])

B = sym.Matrix([[b1, b2],
                [0, b3]])

A

Matrix([
[a_1, a_2],
[  0, a_3]])

In [41]:
B

Matrix([
[b_1, b_2],
[  0, b_3]])

In [42]:
A * B

Matrix([
[a_1*b_1, a_1*b_2 + a_2*b_3],
[      0,           a_3*b_3]])

## 1.2 Transpose and Inverses

### Transpose Matrix

The rows become the columns and the columns become the rows

In terms of individual elements: 

$$
a_{ij}^T = a_{ji}
$$

#### Transpose identities

$
\left(A^{T}\right)^{T} = A
\\
\left(A + B\right)^{T} = A^{T} + B^{T}
\\
\left(AB\right)^{T} = B^{T}A^{T}
$

In [43]:
a11, a12, a13 = sym.symbols('a_11 a_12 a_13')
a21, a22, a23 = sym.symbols('a_21 a_22 a_23')
a31, a32, a33 = sym.symbols('a_31 a_32 a_33')

In [44]:
A = sym.Matrix([[a11, a12, a13],
                [a21, a22, a23],
                [a31, a32, a33]])

A

Matrix([
[a_11, a_12, a_13],
[a_21, a_22, a_23],
[a_31, a_32, a_33]])

In [45]:
A.T

Matrix([
[a_11, a_21, a_31],
[a_12, a_22, a_32],
[a_13, a_23, a_33]])

In [46]:
# numpy
A = np.array([[101, 101, 103],
              [201, 202, 203]])

A.transpose()

array([[101, 201],
       [101, 202],
       [103, 203]])

In [47]:
np.transpose(A)

array([[101, 201],
       [101, 202],
       [103, 203]])

### Symmetric Matrix

- $A^{T} = A$
- A square matrix that is equal to its transpose is called a **symmetric matrix**
- These matrices are symmetric about the diagonal

In [48]:
a, b, c, d, e, f = sym.symbols('a b c d e f')

A = sym.Matrix([[a, b, c],
                [b, d, e],
                [c, e, f]])

A

Matrix([
[a, b, c],
[b, d, e],
[c, e, f]])

In [49]:
A.T

Matrix([
[a, b, c],
[b, d, e],
[c, e, f]])

In [50]:
A == A.T

True

#### Skew-symmetric Matrix

- $A^{T} = -A$
- A square matrix whose transpose is equal to its negative is called a **skew-symmetric matrix**
- The diagonal must contain only 0s. 

In [51]:
a, b, c = sym.symbols('a b c')

A = sym.Matrix([[0, a, b],
                [-a, 0, c],
                [-b, -c, 0]])

A

Matrix([
[ 0,  a, b],
[-a,  0, c],
[-b, -c, 0]])

In [52]:
A.T

Matrix([
[0, -a, -b],
[a,  0, -c],
[b,  c,  0]])

In [53]:
-A

Matrix([
[0, -a, -b],
[a,  0, -c],
[b,  c,  0]])

### Inner and Outer Products

#### Inner Product Between Two Vectors

Let 
$
u = \left[
    \begin{matrix}
        u_{1} \\ 
        u_{2} \\
        \vdots \\
        u_{n}
    \end{matrix}
\right]
$ 
and 
$
v = \left[
    \begin{matrix}
        v_{1} \\ 
        v_{2} \\
        \vdots \\
        v_{n}
    \end{matrix}
\right]
$ 
be two column vectors. Then the **inner product** or **dot product** of $u$ and $v$ is denoted by $u^{T} \cdot v$.

$
\begin{align}
u^{T} \cdot v 
&= 
\left[
    \begin{matrix}
    u_{1} & u_{2} & \dots & u_{n} 
\end{matrix}
\right] 
\cdot 
\left[
    \begin{matrix}
    v_{1} \\ 
    v_{2} \\
    \vdots \\
    v_{n}
\end{matrix}
\right] \\
&= 
u_{1}v_{1} + u_{2}v_{2} + \dots + u_{n}v_{n}
\end{align}
$

- If $u^{T}v = 0$ then $u$ and $v$ are **orthogonal**
- The **norm** of a vector, or its magnitude:

$$
||u|| = \left(u^{T}u\right)^{\frac{1}{2}}
$$

- We say that vectors are **normalized** if $||u|| = 1$
- If two normalized vectors are orthogonal we say that the vectors are **orthonormal**

In [54]:
# normalize a vector
x1, x2, x3 = sym.symbols('x_1 x_2 x_3')
x = sym.Matrix([[x1],
                [x2],
                [x3]])

normalized_x = x / sym.sqrt(x.dot(x))
normalized_x

Matrix([
[x_1/sqrt(x_1**2 + x_2**2 + x_3**2)],
[x_2/sqrt(x_1**2 + x_2**2 + x_3**2)],
[x_3/sqrt(x_1**2 + x_2**2 + x_3**2)]])

In [55]:
len_normalized_x = sym.sqrt(normalized_x.dot(normalized_x))
len_normalized_x.simplify()

1

In [56]:
u1, u2, u3, v1, v2, v3 = sym.symbols('u_1 u_2 u_3 v_1 v_2 v_3')

u = sym.Matrix([[u1],
                [u2],
                [u3]])

v = sym.Matrix([[v1],
                [v2],
                [v3]])

In [57]:
(u.T * v)[0]

u_1*v_1 + u_2*v_2 + u_3*v_3

In [58]:
u.dot(v)

u_1*v_1 + u_2*v_2 + u_3*v_3

In [59]:
# numpy 

u = np.array([[1],
              [2],
              [3]])

v = np.array([[4],
              [5],
              [6]])

In [60]:
u.reshape(-1).dot(v.reshape(-1))

32

In [61]:
np.inner(u.reshape(-1), v.reshape(-1))

32

In [62]:
# sympy
u_sym = sym.Matrix(u)
v_sym = sym.Matrix(v)

In [63]:
(u_sym.T * v_sym)[0]

32

In [64]:
u_sym.dot(v_sym)

32

#### Outer Product Between Two Vectors

In [65]:
u1, u2, u3, v1, v2, v3 = sym.symbols('u_1 u_2 u_3 v_1 v_2 v_3')

u = sym.Matrix([[u1],
                [u2],
                [u3]])

v = sym.Matrix([[v1],
                [v2],
                [v3]])

In [66]:
u * v.T

Matrix([
[u_1*v_1, u_1*v_2, u_1*v_3],
[u_2*v_1, u_2*v_2, u_2*v_3],
[u_3*v_1, u_3*v_2, u_3*v_3]])

### Example of a Symmetric Matrix

Let A be a rectangular matrix given by:

In [67]:
a, b, c, d, e, f = sym.symbols('a b c d e f')

A = sym.Matrix([[a, d],
                [b, e],
                [c, f]])
A

Matrix([
[a, d],
[b, e],
[c, f]])

Compute $A^{T}A$ and show that it is a symmetric matrix and that the sum of its diagonal elements is the sum of the squares of all the elements of $A$

In [68]:
C = A.T * A
C

Matrix([
[a**2 + b**2 + c**2,    a*d + b*e + c*f],
[   a*d + b*e + c*f, d**2 + e**2 + f**2]])

In [69]:
C.is_symmetric()

True

In [70]:
sum_diagonals_of_C = sym.Add()

for i in range(C.rows):
    for j in range(C.cols):
        if i == j:
            sum_diagonals_of_C += C[i, j]

sum_diagonals_of_C.simplify()

a**2 + b**2 + c**2 + d**2 + e**2 + f**2

In [71]:
sum_squares_elements_of_A = sym.Add()

for i in range(A.rows):
    for j in range(A.cols):
        sum_squares_elements_of_A += (A[i, j])**2

sum_squares_elements_of_A

a**2 + b**2 + c**2 + d**2 + e**2 + f**2

In [72]:
# Reading; Sume of the Squores of the Elements of a Matrix: about Tr